stages:
  - test
  - publish
  - publish_external

image: node:10.15.0

test_icons:
  stage: test
  before_script:
    - npm install
    - npm i -g grunt
  script:
    - grunt test

npm_publish:
  stage: publish
  script:
    - npm install
    - npx semantic-release
  when: manual
  only:
    - master

update:rubygem:
  stage: publish_external
  needs: ['npm_publish']
  script:
    - echo "Publishing Ruby Gem"
  trigger:
    project: SUSE-UIUX/eos-icons-rails
    strategy: depend
  only:
    - master

update:iconspage:
  stage: publish_external
  needs: ['npm_publish']
  script:
    - echo "Updating npm dependencies in EOS icons page"
  trigger:
    project: SUSE-UIUX/eos-icons-landing
    strategy: depend
  only:
    - master

update:iconpicker:
  stage: publish_external
  needs: ['npm_publish']
  script:
    - echo "Updating npm dependencies in EOS icons picker"
  trigger:
    project: SUSE-UIUX/eos-icon-picker
    strategy: depend
  only:
    - master
