stages:
  - test
  - publish

image: node:10.15.0

test_icons:
  stage: test
  before_script:
    - npm install
    - npm i -g grunt
  script:
    - grunt test

# Start the jobs

npm_publish:
  stage: publish
  script:
    - npm install
    - npx semantic-release
  when: manual
  only:
    - master

update-ruby-gem:
  stage: test
  needs:
    - job: test_icons
  script:
    - echo "JOB STARTED"
  # trigger:
  #   project: SUSE-UIUX/eos-icons-rails
  #   strategy: depend
