stages:
  - test
  - publish
  - publish_external

image: node:10.15.0

test_icons:
  stage: test
  before_script:
    - npm install
    - npm i -g grunt
  script:
    - grunt test

update:test:
  stage: test
  script:
    - echo "1- This is triggered manually"
  when: manual

npm_publish:
  stage: publish
  script:
    - npm install
    - npx semantic-release
  when: manual
  only:
    - master

update:rubygem:
  stage: publish_external
  needs: [update:test]
  script:
    - echo "2- JOB STARTED"
  # trigger:
  #   project: SUSE-UIUX/eos-icons-rails
  #   strategy: depend
  # only:
  #   - master
